"""phase1b core tables entity observation_log knowledge_state

Revision ID: f215450ec0a6
Revises: 
Create Date: 2026-07-11 15:09:19.402806

"""
from typing import Sequence, Union
from datetime import datetime, timezone
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f215450ec0a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- Discriminated-union value CHECK contracts -------------------------------
# value_raw = feature 原始值原貌 only (never fetch/inference evidence).
# The typed columns (value_text/number/boolean/json/entity_id) hold exactly one
# value matching value_type when observed.

# observation_log layer 1: status ↔ value_raw (observed non-null AND non-blank).
_CK_OBS_VALUE_RAW = (
    "(status = 'observed' AND value_raw IS NOT NULL AND btrim(value_raw) <> '') "
    "OR (status IN ('fetch_failed', 'not_found') AND value_raw IS NULL)"
)

# observation_log layer 2: status ↔ value_type ↔ typed columns.
# value_type is retained on failed/not_found (it describes the expected type).
_CK_OBS_TYPED = """
(status = 'observed' AND (
    (value_type = 'string'     AND value_text IS NOT NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NULL)
    OR (value_type = 'number'     AND value_text IS NULL AND value_number IS NOT NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NULL)
    OR (value_type = 'boolean'    AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NOT NULL AND value_json IS NULL AND value_entity_id IS NULL)
    OR (value_type = 'json'       AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NOT NULL AND value_entity_id IS NULL)
    OR (value_type = 'entity_ref' AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NOT NULL)
))
OR
(status IN ('fetch_failed', 'not_found')
    AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NULL)
"""

# knowledge_state only projects observed rows: no status, no failed branch.
_CK_KNOWLEDGE_VALUE_RAW = "value_raw IS NOT NULL AND btrim(value_raw) <> ''"
_CK_KNOWLEDGE_TYPED = """
(value_type = 'string'     AND value_text IS NOT NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NULL)
OR (value_type = 'number'     AND value_text IS NULL AND value_number IS NOT NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NULL)
OR (value_type = 'boolean'    AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NOT NULL AND value_json IS NULL AND value_entity_id IS NULL)
OR (value_type = 'json'       AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NOT NULL AND value_entity_id IS NULL)
OR (value_type = 'entity_ref' AND value_text IS NULL AND value_number IS NULL AND value_boolean IS NULL AND value_json IS NULL AND value_entity_id IS NOT NULL)
"""


# ReviewApp Signature Library v1 (Feature Taxonomy v1). Seeded as known
# 'review_app' entities. Fixed UUIDs so re-running upgrade/downgrade is stable.
REVIEW_APP_SEEDS = [
    {"entity_id": uuid.UUID("11111111-1111-4111-8111-000000000001"), "canonical_key": "loox"},
    {"entity_id": uuid.UUID("11111111-1111-4111-8111-000000000002"), "canonical_key": "judgeme"},
    {"entity_id": uuid.UUID("11111111-1111-4111-8111-000000000003"), "canonical_key": "yotpo"},
    {"entity_id": uuid.UUID("11111111-1111-4111-8111-000000000004"), "canonical_key": "okendo"},
    {"entity_id": uuid.UUID("11111111-1111-4111-8111-000000000005"), "canonical_key": "stamped"},
]

# Append-Only physical lock for observation_log: reject UPDATE and DELETE at the
# DB layer. This is the 唯一真相 table; Append-Only is enforced by the DB, not by
# discipline. knowledge_state (物化視圖) is deliberately NOT locked — it must
# UPDATE. entity is a plain table.
_APPEND_ONLY_FN = """
CREATE OR REPLACE FUNCTION mes_reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'observation_log is append-only: % is not allowed', TG_OP;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('store', 'review_app', 'store_name_seed')", name='ck_entity_entity_type'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_type', 'canonical_key', name='uq_entity_type_canonical_key')
    )
    op.create_table('observation_log',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(), nullable=True),
    sa.Column('value_entity_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('crawler_version', sa.String(length=64), nullable=True),
    sa.CheckConstraint("confidence IN ('certain', 'inferred', 'estimated')", name='ck_observation_confidence'),
    sa.CheckConstraint("source IN ('html_page', 'products_json', 'html_signature', 'manual', 'monitor')", name='ck_observation_source'),
    sa.CheckConstraint("status IN ('observed', 'fetch_failed', 'not_found')", name='ck_observation_status'),
    sa.CheckConstraint("value_type IN ('string', 'number', 'boolean', 'entity_ref', 'json')", name='ck_observation_value_type'),
    sa.CheckConstraint(_CK_OBS_VALUE_RAW, name='ck_observation_value_raw_status'),
    sa.CheckConstraint(_CK_OBS_TYPED, name='ck_observation_value_typed'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.ForeignKeyConstraint(['value_entity_id'], ['entity.entity_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('knowledge_state',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(), nullable=True),
    sa.Column('value_entity_id', sa.Uuid(), nullable=True),
    sa.Column('source_observation_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('selection_rule_version', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence IN ('certain', 'inferred', 'estimated')", name='ck_knowledge_confidence'),
    sa.CheckConstraint("value_type IN ('string', 'number', 'boolean', 'entity_ref', 'json')", name='ck_knowledge_value_type'),
    sa.CheckConstraint(_CK_KNOWLEDGE_VALUE_RAW, name='ck_knowledge_value_raw'),
    sa.CheckConstraint(_CK_KNOWLEDGE_TYPED, name='ck_knowledge_value_typed'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.ForeignKeyConstraint(['source_observation_id'], ['observation_log.observation_id'], ),
    sa.ForeignKeyConstraint(['value_entity_id'], ['entity.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'feature')
    )
    # ### end Alembic commands ###

    # --- Append-Only physical lock on observation_log (決定三) ---------------
    op.execute(_APPEND_ONLY_FN)
    op.execute(
        "CREATE TRIGGER observation_log_no_update "
        "BEFORE UPDATE ON observation_log "
        "FOR EACH ROW EXECUTE FUNCTION mes_reject_mutation();"
    )
    op.execute(
        "CREATE TRIGGER observation_log_no_delete "
        "BEFORE DELETE ON observation_log "
        "FOR EACH ROW EXECUTE FUNCTION mes_reject_mutation();"
    )

    # --- Seed: ReviewApp Signature Library v1 as known review_app entities ----
    entity_table = sa.table(
        "entity",
        sa.column("entity_id", sa.Uuid()),
        sa.column("entity_type", sa.String()),
        sa.column("canonical_key", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    seeded_at = datetime.now(timezone.utc)
    op.bulk_insert(
        entity_table,
        [
            {
                "entity_id": seed["entity_id"],
                "entity_type": "review_app",
                "canonical_key": seed["canonical_key"],
                "created_at": seeded_at,
            }
            for seed in REVIEW_APP_SEEDS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS observation_log_no_delete ON observation_log;")
    op.execute("DROP TRIGGER IF EXISTS observation_log_no_update ON observation_log;")
    op.execute("DROP FUNCTION IF EXISTS mes_reject_mutation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_state')
    op.drop_table('observation_log')
    op.drop_table('entity')
    # ### end Alembic commands ###
